- alias: /HDPDocuments/Ambari/latest/
  exist: /HDPDocuments/Ambari/Ambari-2.7.5.0/
- alias: /HDPDocuments/Ambari-latest/
  exist: /HDPDocuments/Ambari-2.7.5.0/
- alias: /HDPDocuments/Cloudbreak/latest/
  exist: /HDPDocuments/Cloudbreak/Cloudbreak-2.9.1/
- alias: /HDPDocuments/DAS/latest/
  exist: /HDPDocuments/DAS/DAS-1.4.5/
- alias: /HDPDocuments/DLM1/latest/
  exist: /HDPDocuments/DLM1/DLM-1.5.1/
- alias: /HDPDocuments/DP/latest/
  exist: /HDPDocuments/DP/DP-1.3.0/
- alias: /HDPDocuments/DSS1/latest/
  exist: /HDPDocuments/DSS1/DSS-1.6.1/
- alias: /HDPDocuments/HCP1/latest/
  exist: /HDPDocuments/HCP1/HCP-1.9.1/
- alias: /HDPDocuments/HDF1/latest/
  exist: /HDPDocuments/HDF1/HDF-1.2.1/
- alias: /HDPDocuments/HDF2/latest/
  exist: /HDPDocuments/HDF2/HDF-2.1.4/
- alias: /HDPDocuments/HDF3/HDF-3.5.0/
  exist: /HDPDocuments/HDF3/HDF-3.5.1/
- alias: /HDPDocuments/HDF3/latest/
  exist: /HDPDocuments/HDF3/HDF-3.5.1/
- alias: /HDPDocuments/HDP1/latest/
  exist: /HDPDocuments/HDP1/HDP-1.3.10/
- alias: /HDPDocuments/HDP2/latest/
  exist: /HDPDocuments/HDP2/HDP-2.6.5/
- alias: /HDPDocuments/HDP3/latest/
  exist: /HDPDocuments/HDP3/HDP-3.1.5/
- alias: /HDPDocuments/HDPforCloud/latest/
  exist: /HDPDocuments/HDPforCloud/HDPforCloud-3.1/
- alias: /HDPDocuments/HDPS/latest/
  exist: /HDPDocuments/HDPS/HDPS-5.0.0/
- alias: /HDPDocuments/SS1/latest/
  exist: /HDPDocuments/SS1/SmartSense-1.5.1/

- alias: /cdpdc/latest/
  exist: /cdp/latest/
- alias: /cdp/cloud/
  exist: /cdp/latest/

- alias: /cem/latest/
  exist: /cem/1.1.1/
- alias: /cfm/latest/
  exist: /cfm/1.1.0/
- alias: /cloudera-manager/latest/
  exist: /cloudera-manager/7.1.1/
- alias: /csa/latest/
  exist: /csa/1.2.0/
- alias: /csp/latest/
  exist: /csp/2.0.1/
- alias: /cdf-datahub/latest/
  exist: /cdf-datahub/7.1.0/

- alias: /documentation/data-science-workbench/latest/
  exist: /documentation/data-science-workbench/1-7-x/
- alias: /documentation/data-science-workbench/latest.html
  exist: /documentation/data-science-workbench/1-7-x.html

- alias: /documentation/director/latest/
  exist: /documentation/director/6-3-x/
- alias: /documentation/director/latest.html
  exist: /documentation/director/6-3-x.html

- alias: /documentation/enterprise/5/latest/
  exist: /documentation/enterprise/5-16-x/
- alias: /documentation/enterprise/6/latest/
  exist: /documentation/enterprise/6/6.3/
- alias: /documentation/enterprise/latest/
  exist: /documentation/enterprise/6/6.3/

- alias: /documentation/kafka/latest/
  exist: /documentation/kafka/4-1-x/
- alias: /documentation/kafka/latest.html
  exist: /documentation/kafka/4-1-x.html

- alias: /documentation/other/accumulo/latest/
  exist: /documentation/other/accumulo/1-9-2/
- alias: /documentation/other/accumulo/latest.html
  exist: /documentation/other/accumulo/1-9-2.html

- alias: /documentation/other/connectors/hive-jdbc/latest/
  exist: /documentation/other/connectors/hive-jdbc/2-6-9/
- alias: /documentation/other/connectors/hive-jdbc/latest.html
  exist: /documentation/other/connectors/hive-jdbc/2-6-9.html

- alias: /documentation/other/connectors/hive-odbc/latest/
  exist: /documentation/other/connectors/hive-odbc/2-6-5/
- alias: /documentation/other/connectors/hive-odbc/latest.html
  exist: /documentation/other/connectors/hive-odbc/2-6-5.html

# Check to assure we have content for
#   /documentation/other/connectors/hive-odbc/2-6-1/

- alias: /documentation/other/connectors/impala-jdbc/latest/
  exist: /documentation/other/connectors/impala-jdbc/2-6-15/
- alias: /documentation/other/connectors/impala-jdbc/latest.html
  exist: /documentation/other/connectors/impala-jdbc/2-6-15.html

- alias: /documentation/other/connectors/impala-odbc/latest/
  exist: /documentation/other/connectors/impala-odbc/2-6-9/
- alias: /documentation/other/connectors/impala-odbc/latest.html
  exist: /documentation/other/connectors/impala-odbc/2-6-9.html

- alias: /documentation/spark2/latest/
  exist: /documentation/spark2/2-4-x/
- alias: /documentation/spark2/latest.html
  exist: /documentation/spark2/2-4-x.html

- alias: /content/www/en-us/documentation/
  exist: /documentation/

# /documentation/wxm/latest/ is not an alias

- alias: /runtime/latest/
  exist: /runtime/7.1.1/
- alias: /smm/latest/
  exist: /smm/2.0.0/
- alias: /srm/latest/
  exist: /srm/1.0.0/

# Cloudera Enterprise Upgrade Guide

- alias: /documentation/enterprise/5-3-x/PDF/cloudera-upgrade.pdf
  exist: /documentation/enterprise/upgrade/PDF/cloudera-ug_upgrade.pdf
- alias: /documentation/enterprise/5-4-x/PDF/cloudera-upgrade.pdf
  exist: /documentation/enterprise/upgrade/PDF/cloudera-ug_upgrade.pdf
- alias: /documentation/enterprise/5-5-x/PDF/cloudera-upgrade.pdf
  exist: /documentation/enterprise/upgrade/PDF/cloudera-ug_upgrade.pdf
- alias: /documentation/enterprise/5-6-x/PDF/cloudera-upgrade.pdf
  exist: /documentation/enterprise/upgrade/PDF/cloudera-ug_upgrade.pdf
- alias: /documentation/enterprise/5-7-x/PDF/cloudera-upgrade.pdf
  exist: /documentation/enterprise/upgrade/PDF/cloudera-ug_upgrade.pdf
- alias: /documentation/enterprise/5-8-x/PDF/cloudera-upgrade.pdf
  exist: /documentation/enterprise/upgrade/PDF/cloudera-ug_upgrade.pdf
- alias: /documentation/enterprise/5-9-x/PDF/cloudera-upgrade.pdf
  exist: /documentation/enterprise/upgrade/PDF/cloudera-ug_upgrade.pdf
- alias: /documentation/enterprise/5-10-x/PDF/cloudera-upgrade.pdf
  exist: /documentation/enterprise/upgrade/PDF/cloudera-ug_upgrade.pdf
- alias: /documentation/enterprise/5-11-x/PDF/cloudera-upgrade.pdf
  exist: /documentation/enterprise/upgrade/PDF/cloudera-ug_upgrade.pdf
- alias: /documentation/enterprise/5-12-x/PDF/cloudera-upgrade.pdf
  exist: /documentation/enterprise/upgrade/PDF/cloudera-ug_upgrade.pdf
- alias: /documentation/enterprise/5-13-x/PDF/cloudera-upgrade.pdf
  exist: /documentation/enterprise/upgrade/PDF/cloudera-ug_upgrade.pdf
- alias: /documentation/enterprise/5-14-x/PDF/cloudera-upgrade.pdf
  exist: /documentation/enterprise/upgrade/PDF/cloudera-ug_upgrade.pdf
- alias: /documentation/enterprise/5-15-x/PDF/cloudera-upgrade.pdf
  exist: /documentation/enterprise/upgrade/PDF/cloudera-ug_upgrade.pdf
- alias: /documentation/enterprise/5-16-x/PDF/cloudera-upgrade.pdf
  exist: /documentation/enterprise/upgrade/PDF/cloudera-ug_upgrade.pdf
