# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog,
# values which you are expected to set up once and rarely edit after
# that. If you find yourself editing this file very often, consider
# using Jekyll's data files feature for the data you need to update
# frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when
# you use 'bundle exec jekyll serve'. If you change this file, please
# restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML
# files, you will see them accessed via {{ site.title }}, {{ site.email
# }}, and so on. You can create any custom variable you would like, and
# they will be accessible in the templates via {{ site.myvariable }}.
title: Cloudera Docs
email: docs@cloudera.com
description: >- # this means to ignore newlines until "baseurl:"
  Cloudera technical documentation
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://docs-stage.cloudera.com"
twitter_username: cloudera
github_username:  cloudera

# Build settings
markdown: kramdown
#theme: minima
#plugins:
#  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - /Gemfile
  - /Gemfile.lock
  - /README.md

  # "master" version for docs-dev only
  - /cdp/master/
  - /data-catalog/master/
  - /data-hub/master/
  - /data-warehouse/master/
  - /machine-learning/master/
  - /management-console/master/
  - /replication-manager/master/
  - /workload-manager/master/
  - /runtime/master/
  - /cloudera-manager/master/
  - /cem/master/
  - /cfm/master/
  - /csp/master/
  - /smm/master/
  - /srm/master/

  # Static content that doesn't need to be part of most builds
  - /common/fonts/
  - /common/img/
  - /common/js/libs/
  - /common/sample-data/
  - /common/themes/pre-hdp-3.1/
  - /favicon.ico
  - /sitemap.xsl

  # REST API Pages
  - /cem/1.0.0/rest-api-reference/
  - /cem/1.1.0/rest-api-reference/
  # - /csp/2.0.0/smm-rest-api-reference/
  # - /csp/2.0.0/srm-rest-api-reference/
  - /smm/1.0.0/rest-api-reference/
  - /smm/1.1.0/rest-api-reference/
  - /smm/1.2.0/rest-api-reference/
  - /smm/1.2.1/rest-api-reference/
  - /smm/2.0.0/rest-api-reference/
  - /srm/1.0.0/rest-api-reference/

  # Static content supporting the legacy Hortonworks pages that don't
  # need to be part of most builds
  - /google313e059f6e26cb8c.html
  - /googlea675d981988e7c7a.html
  - /HDPDocuments/Cloudbreak/Cb-doc-resources/
  - /wp-content

  # Static content supporting the legacy Cloudera pages that don't need
  # to be part of most builds
  - /apps/
  - /content/
  - /etc/
  - /etc.clientlibs/
  - /libs/

  # For development to speed up jekyll compile times, uncomment the following....
  # - /HDPDocuments/
  # - /documentation/
