# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Cloudera Docs
email: docs@cloudera.com
description: >- # this means to ignore newlines until "baseurl:"
  Cloudera technical documentation
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://docs-dev.cloudera.com"
twitter_username: cloudera
github_username:  cloudera

# Build settings
markdown: kramdown
#theme: minima
#plugins:
#  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
#  Unreleased documentation
  - HDPDocuments/CFM/CFM-1.1.0/
  - HDPDocuments/DAS/DAS-1.3.0/
  - HDPDocuments/DLM1/DLM-1.5.0/
  - HDPDocuments/DPS/
  - HDPDocuments/HDF3/HDF-3.5.0/
  - HDPDocuments/SMM/SMM-2.0.0/
# Testing files that should not be copied to the hortonworks staging site
  - data-catalog/cloud/navigation.json
  - data-hub/cloud/navigation.json
  - machine-learning/cloud/navigation.json
  - management-console/cloud/navigation.json
  - replication-manager/cloud/navigation.json
  - runtime/7.0.0/navigation.json

# Testing files that should not be copied to any s3 bucket
  - hdf
  - runtime/7.0.0/integrating-hive-and-bi/
  - runtime/7.0.0/managing-a-hive-workload/
  - runtime/7.0.0/managing-hive/
  - runtime/7.0.0/securing-hive/
  - runtime/7.0.0/starting-hive/
  - runtime/7.0.0/using-hiveql/
