# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Cloudera Docs
email: docs@cloudera.com
description: >- # > = ignore newlines til "baseurl:"; - = omit final newline
  Cloudera technical documentation
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://docs.hortonworks.com" # the base hostname & protocol for your site
twitter_username: cloudera
github_username:  cloudera
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

# Build settings
markdown: kramdown
defaults:
  - scope:
      path: ''
      type: navigation
    values:
      layout: json
