#!/usr/env ruby -w
# frozen_string_literal: true

# Create client-side redirects for www.cloudera destinations referenced
# from (legacy) cloudera documentation. Whenever a link starts with a
# slash (under the expection the URL references a resource on the
# www.cloudera.com site) we can redirect to the equivalent
# www.cloudera.com resource.

require 'erb'
require 'fileutils'

template = '<meta http-equiv="refresh" content="0; URL=<%= @redirect %>">'
# template = '<!DOCTYPE html>
#   <html lang="en">
#   <head>
#   <meta charset="UTF-8">
#   <title>Moved</title>
#   <meta http-equiv="refresh" content="0; URL=<%= @redirect %>">
#   </head>
#   <body>
#   <p></p>
#   </body>
#   </html>
# '.gsub(/^  /, '')

# Remember, the following do NOT take the same pattern redirect as the
# others:
#   index.html (new docs homepage)
#   documentation.html (/documentation/index.html)
#   downloads.html.html (/downloads.html)
# Keep them out of the list below.
redirects = %w[
  about.html
  about/careers.html
  about/customers.html
  about/customers/8x8.html
  about/customers/aci-worldwide.html
  about/customers/adp.html
  about/customers/allegis.html
  about/customers/atb-financial.html
  about/customers/banco-santander-spain.html
  about/customers/bank-danamon.html
  about/customers/bank-mandiri.html
  about/customers/bank-of-england.html
  about/customers/bcp.html
  about/customers/bharti-airtel.html
  about/customers/bidtellect.html
  about/customers/bt.html
  about/customers/caesarsentertainment.html
  about/customers/carlson-wagonlit-travel.html
  about/customers/cartao-elo.html
  about/customers/centrica.html
  about/customers/cerner.html
  about/customers/cisco.html
  about/customers/clearsense.html
  about/customers/cloudera-engaged.html
  about/customers/cloudera-support-interface.html
  about/customers/connexity.html
  about/customers/conversant.html
  about/customers/countertack.html
  about/customers/cox-automotive.html
  about/customers/credit-suisse.html
  about/customers/csc.html
  about/customers/cybraics.html
  about/customers/data-impact-awards.html
  about/customers/dbs-bank.html
  about/customers/dell.html
  about/customers/deutsche-telekom.html
  about/customers/dhisco.html
  about/customers/dish.html
  about/customers/docbox.html
  about/customers/docomo-digital.html
  about/customers/drawbridge.html
  about/customers/emirates-nbd.html
  about/customers/epsilon.html
  about/customers/equifax.html
  about/customers/experian.html
  about/customers/faurecia.html
  about/customers/fireeye.html
  about/customers/freddie-mac.html
  about/customers/geisinger.html
  about/customers/glaxosmithkline.html
  about/customers/globe-telecom.html
  about/customers/greentube.html
  about/customers/hellofresh.html
  about/customers/hilton.html
  about/customers/hotels-com.html
  about/customers/impact-radius.html
  about/customers/inova.html
  about/customers/iqvia.html
  about/customers/jido.html
  about/customers/jobrapido.html
  about/customers/johns-hopkins-university.html
  about/customers/kasikorn-bank.html
  about/customers/klarna.html
  about/customers/komatsu-mining.html
  about/customers/lufthansa-technik.html
  about/customers/magnify.html
  about/customers/markerstudy.html
  about/customers/mastercard.html
  about/customers/mbank.html
  about/customers/mesurio.html
  about/customers/micron.html
  about/customers/mitre.html
  about/customers/mitsubishi-fuso.html
  about/customers/national-childrens-hospital.html
  about/customers/navistar.html
  about/customers/nissan.html
  about/customers/novantas.html
  about/customers/numberly-mille-mercis-group.html
  about/customers/nyse-ice.html
  about/customers/o2.html
  about/customers/octo-telematics.html
  about/customers/odyssey.html
  about/customers/opower.html
  about/customers/orwell-group.html
  about/customers/patterns-and-predictions.html
  about/customers/persol-career.html
  about/customers/podo.html
  about/customers/prgx.html
  about/customers/pwc-cee.html
  about/customers/qsight-it.html
  about/customers/quaero.html
  about/customers/quanam.html
  about/customers/quest-diagnostics.html
  about/customers/quotient.html
  about/customers/ringcentral.html
  about/customers/rocketroi.html
  about/customers/rowan-companies.html
  about/customers/rush-university-medical-center.html
  about/customers/santander-uk.html
  about/customers/seattle-childrens.html
  about/customers/sfr.html
  about/customers/shoppermotion.html
  about/customers/sikorsky.html
  about/customers/simply-measured.html
  about/customers/sky-bet.html
  about/customers/solocal-group.html
  about/customers/symcor.html
  about/customers/t-mobile-austria.html
  about/customers/td-bank.html
  about/customers/technipfmc.html
  about/customers/telefonica.html
  about/customers/tenaris.html
  about/customers/thomson-reuters.html
  about/customers/tmw-systems.html
  about/customers/transamerica.html
  about/customers/true-corporation.html
  about/customers/unidad-editorial.html
  about/customers/united-overseas-bank.html
  about/customers/vizient.html
  about/customers/wargaming.html
  about/customers/western-union.html
  about/customers/xl-axiata.html
  about/customers/zoomlion.html
  about/customers/zoosk.html
  about/customers/zurich-insurance.html
  about/events.html
  about/events/cloudera-now.html
  about/events/cloudera-summer-school.html
  about/events/edge-to-ai-city-tour.html
  about/events/gov-forum.html
  about/events/modern-data-warehousing-fundamentals.html
  about/events/partners-summit.html
  about/events/sessions.html
  about/events/speaker-series.html
  about/events/trade-shows.html
  about/events/webinars.html
  about/investor-relations.html
  about/leadership.html
  about/locations.html
  about/news-and-blogs.html
  about/news-and-blogs/awards.html
  about/news-and-blogs/blogs.html
  about/news-and-blogs/edge-to-ai.html
  about/news-and-blogs/media-kit.html
  about/news-and-blogs/press-releases.html
  about/partners.html
  about/services-and-support.html
  about/services-and-support/fast-forward-labs.html
  about/services-and-support/professional-services.html
  about/services-and-support/support-offering.html
  about/training.html
  about/training/blended-learning.html
  about/training/certification.html
  about/training/classroom.html
  about/training/cloudera-training-administrator-technical-training-requirements.html
  about/training/cloudera-training-course-prerequisites.html
  about/training/cloudera-training-terms-and-conditions.html
  about/training/course-listing.html
  about/training/courses.html
  about/training/description-of-training-services.html
  about/training/ondemand-training.html
  about/training/private-training.html
  about/training/roles.html
  about/training/testimonials.html
  about/training/training-partner-application.html
  about/training/training-partners.html
  about/training/virtual-classroom.html
  careers.html
  contact-sales.html
  content/dam/www/marketing/resources/analyst-reports/big-data-cybersecurity-analytics-research-report.pdf.landing.html
  content/dam/www/marketing/resources/analyst-reports/DBTA_AprMay2018_BP-evolution-of-analytics.pdf.landing.html
  content/dam/www/marketing/resources/analyst-reports/deep-learning-forrester.pdf.landing.html
  content/dam/www/marketing/resources/analyst-reports/gartner-roadmap-for-it-to-help-drive-machine-learning.landing.html
  content/dam/www/marketing/resources/analyst-reports/tdwi_checklist_2018_Cloudera_Modernizing_Data_Warehouse_Infrastructure.pdf.landing.html
  content/dam/www/marketing/resources/analyst-reports/tdwi-checklist-report-emerging-design-patterns-for-data-management.pdf.landing.html
  content/dam/www/marketing/resources/case-studies/Cloudera_Drawbridge_Case_Study_102_A4.pdf.landing.html
  content/dam/www/marketing/resources/case-studies/lufthansa-customer-success-story.pdf.landing.html
  content/dam/www/marketing/resources/datasheets/cloudera-data-science-workbench-introduction.pdf.landing.html
  content/dam/www/marketing/resources/datasheets/cloudera-enterprise-datasheet.pdf.landing.html
  content/dam/www/marketing/resources/datasheets/cloudera-navigator-datasheet.pdf.landing.html
  content/dam/www/marketing/resources/datasheets/cloudera-security-datasheet.pdf.landing.html
  content/dam/www/marketing/resources/datasheets/gov-proactive-and-predictive-support-overview.pdf.landing.html
  content/dam/www/marketing/resources/datasheets/gov-support-datasheet.pdf.landing.html
  content/dam/www/marketing/resources/demos/cloudera-data-science-workbench-demo.png.landing.html
  content/dam/www/marketing/resources/emea/en/webinars/realism-and-real-time-in-cyber-security-machine-learning.png.landing.html
  content/dam/www/marketing/resources/emea/es/solution-briefs/estudio-de-la-madurez-en-el-uso-de-la-analitica-avanzada-en-el-sector-asegurador.pdf.landing.html
  content/dam/www/marketing/resources/solution-briefs/cloudera-and-tableau-enable-real-time-business-intelligence.pdf.landing.html
  content/dam/www/marketing/resources/solution-briefs/customer-360-powered-by-zero2hero.pdf.landing.html
  content/dam/www/marketing/resources/solution-briefs/seeing-information-more-clearly-with-enterprise-data-cloud-analytics.pdf.landing.html
  content/dam/www/marketing/resources/solution-briefs/zwoox-data-ingestion-made-easy.pdf.landing.html
  content/dam/www/marketing/resources/videos/modernizing-bi-and-analytics.landing.html
  content/dam/www/marketing/resources/webinars/Big-Data-Fundamentals-recorded-webinar.png.landing.html
  content/dam/www/marketing/resources/webinars/Big-Data-Fundamentals-recorded-webinar1.png.landing.html
  content/dam/www/marketing/resources/webinars/cdsw-office-hours-series-part1.png.landing.html
  content/dam/www/marketing/resources/webinars/cdsw-office-hours-series-part2.png.landing.html
  content/dam/www/marketing/resources/webinars/cloud-computing-in-retail-webinar.png.landing.html
  content/dam/www/marketing/resources/webinars/Cloudera-Data-Science-Workbench-sparklyr-implyr-and-More-dplyr-Interfaces-to-Large-scale-Data-recorded-webinar.png.landing.html
  content/dam/www/marketing/resources/webinars/cloudera-fast-forward-labs-accelerate-machine-learning-recorded-webinar.png.landing.html
  content/dam/www/marketing/resources/webinars/cloudera-fast-forward-labs-building-a-better-recommendation-system-recorded-webinar.png.landing.html
  content/dam/www/marketing/resources/webinars/cloudera-sdx-consistent-security-recorded-webinar.png.landing.html
  content/dam/www/marketing/resources/webinars/clouderas-new-cloud-native-platform.png.landing.html
  content/dam/www/marketing/resources/webinars/Consolidate-your-data-marts-for-fast-flexible-analytics-recorded-webinar.png.landing.html
  content/dam/www/marketing/resources/webinars/data_driven_enterprises_run_the_cloudera_modern_data_warehouse.png.landing.html
  content/dam/www/marketing/resources/webinars/data_in_motion_tech_launch_showcase.png.landing.html
  content/dam/www/marketing/resources/webinars/data-driven-transformation-for-telcos.png.landing.html
  content/dam/www/marketing/resources/webinars/dbta-edge-management-gaining-value-from-iot.png.landing.html
  content/dam/www/marketing/resources/webinars/deep-learning-with-cloudera-webinar.png.landing.html
  content/dam/www/marketing/resources/webinars/Demystifying-ML-&-AI-recorded-webinar.png.landing.html
  content/dam/www/marketing/resources/webinars/doing-a-180-on-customer-360-recorded-webinar.png.landing.html
  content/dam/www/marketing/resources/webinars/experience-the-first-hybrid-multi-cloud-data-warehouse-on-cdp.png.landing.html
  content/dam/www/marketing/resources/webinars/extending-cloudera-sdx-beyond-the-platform-recorded-webinar.png.landing.html
  content/dam/www/marketing/resources/webinars/federated-learning-ml-recorded-webinar.png.landing.html
  content/dam/www/marketing/resources/webinars/harnessing-the-cloud-for-big-data-insights-emea.png.landing.html
  content/dam/www/marketing/resources/webinars/hbr-cybersecurity-for-the-c-suite.png.landing.html
  content/dam/www/marketing/resources/webinars/hive-impala-and-spark-oh-my-sql-on-Hadoop-in-cloudera-5-5.png.landing.html
  content/dam/www/marketing/resources/webinars/how_sdi_modernized_supply_chain_data.png.landing.html
  content/dam/www/marketing/resources/webinars/impala-unlocks-interactive-bi-on-hadoop-slide-deck.png.landing.html
  content/dam/www/marketing/resources/webinars/industrialize-ai-with-enterprise-scale-machine-learning-recorded-webinar.png.landing.html
  content/dam/www/marketing/resources/webinars/industrialize-ai-with-enterprise-scale-machine-learning-recorded-webinar1.png.landing.html
  content/dam/www/marketing/resources/webinars/information-management-atscale-gsk-toyota-succeed-with-bi-on-the-data-lake.landing.html
  content/dam/www/marketing/resources/webinars/introducing-cdsw-1.6-an-new-ml-services.png.landing.html
  content/dam/www/marketing/resources/webinars/introducing-cdsw-for-hdp.png.landing.html
  content/dam/www/marketing/resources/webinars/introducing-cloudera-dataflow.png.landing.html
  content/dam/www/marketing/resources/webinars/kafka-power-chat-challenges-in-streaming-architectures.png.landing.html
  content/dam/www/marketing/resources/webinars/leveraging-the-cloud-for-analytics-and-ml.png.landing.html
  content/dam/www/marketing/resources/webinars/leveraging-the-cloud-for-big-data-analytics-recorded-webinar.png.landing.html
  content/dam/www/marketing/resources/webinars/leveraging-the-cloud-for-precision-medicine-and-more.png.landing.html
  content/dam/www/marketing/resources/webinars/live-cloudera-cybersecurity-solution-demo.png.landing.html
  content/dam/www/marketing/resources/webinars/Machine-Learning-Models-From-Research-to-Production-recorded-webinar.png.landing.html
  content/dam/www/marketing/resources/webinars/Making-Self-Service-BI-a-Reality-in-the-Enterprise-recorded-webinar.png.landing.html
  content/dam/www/marketing/resources/webinars/mit-sloan-webinar-five-strategies-for-getting-the-most-from-ai.landing.html
  content/dam/www/marketing/resources/webinars/modern-data-strategy-for-regional-and-mid-size-banks-webinar.png.landing.html
  content/dam/www/marketing/resources/webinars/modern-data-warehousing-fundamentals-recorded-webinar.png.landing.html
  content/dam/www/marketing/resources/webinars/SDX-GDPR-webinar.jpg.landing.html
  content/dam/www/marketing/resources/webinars/shortening-the-sales-cycle-with-a-modern-data-warehouse.png.landing.html
  content/dam/www/marketing/resources/webinars/simplify-your-response-to-gdpr-webinar.png.landing.html
  content/dam/www/marketing/resources/webinars/speed-flexibility-intelligence-beyond-the-traditional-data-warehouse.png.landing.html
  content/dam/www/marketing/resources/webinars/supercharge-splunk-with-cloudera.png.landing.html
  content/dam/www/marketing/resources/webinars/the-future-of-data-warehousing--etl-will-never-be-the-same.png.landing.html
  content/dam/www/marketing/resources/webinars/things-we-bet-you-didnt-know-your-cloudera-data-warehouse-can-do.png.landing.html
  content/dam/www/marketing/resources/webinars/video--hadoop-security-iii---protecting-data-at-rest-and-in-moti.png.landing.html
  content/dam/www/marketing/resources/webinars/video--hadoop-security-iv---visibility-through-a-single-end-to-e.png.landing.html
  content/dam/www/marketing/resources/webinars/Whats-New-in-Cloudera-Enterprise-6.0-The-Inside-Scoop-recorded-webinar.png.landing.html
  content/dam/www/marketing/resources/whitepapers/12-requirements-for-a-modern-data-architecture-in-a-hybrid-cloud-world.pdf.landing.html
  content/dam/www/marketing/resources/whitepapers/apache-impala-incubating-analytic-database-for-apache-hadoop-technical-ebook.pdf.landing.html
  content/dam/www/marketing/resources/whitepapers/Cloudera_Deep_Learning.pdf.landing.html
  content/dam/www/marketing/resources/whitepapers/cloudera-enterprise-whitepaper.pdf.landing.html
  content/dam/www/marketing/resources/whitepapers/cloudera-gdpr-whitepaper.pdf.landing.html
  content/dam/www/marketing/resources/whitepapers/cloudera-lowering-business-risk-with-data.pdf.landing.html
  content/dam/www/marketing/resources/whitepapers/cybersecurity-sourcebook-2017.pdf.landing.html
  content/dam/www/marketing/resources/whitepapers/five-steps-for-aligning-data-and-hybrid-cloud-architectures.pdf.landing.html
  content/dam/www/marketing/resources/whitepapers/idg-building-a-data-driven-enterprise.pdf.landing.html
  content/dam/www/marketing/resources/whitepapers/modern-data-platform-for-cloud-cloudera-whitepaper.pdf.landing.html
  content/dam/www/marketing/resources/whitepapers/operational-database-whitepaper.pdf.landing.html
  content/dam/www/marketing/resources/whitepapers/power-your-business-transformation-with-edc.pdf.landing.html
  content/dam/www/marketing/resources/whitepapers/Qlik_Cloudera_BigData_eBook_020818.pdf.landing.html
  content/dam/www/marketing/resources/whitepapers/why-open-source-matters.pdf.landing.html
  developers/get-started-with-hadoop-tutorial.html
  developers/hadoop-ecosystem-books.html
  downloads.html
  downloads/cdf.html
  downloads/cdf/config.html
  downloads/cdf/csp-trial.html
  downloads/cdf/csp.html
  downloads/cdh/6-2-0.html
  downloads/connectors/hive/jdbc/2-5-15.html
  downloads/connectors/impala/jdbc/2-5-5.html
  downloads/director.html
  downloads/director/1-5-2.html
  downloads/director/2-5-0.html
  downloads/director/2-5-1.html
  downloads/director/2-6-0.html
  downloads/director/2-6-1.html
  downloads/director/2-7-0.html
  downloads/director/2-7-1.html
  downloads/director/2-8-0.html
  downloads/director/2-8-1.html
  downloads/director/6-0-0.html
  downloads/director/6-0-1.html
  downloads/director/6-1-0.html
  downloads/director/6-2-0.html
  downloads/director/6-2-1.html
  downloads/manager.html
  downloads/manager/5-10-0.html
  downloads/manager/5-10-1.html
  downloads/manager/5-10-2.html
  downloads/manager/5-11-0.html
  downloads/manager/5-11-1.html
  downloads/manager/5-11-2.html
  downloads/manager/5-12-0.html
  downloads/manager/5-12-1.html
  downloads/manager/5-13-3.html
  downloads/manager/5-14-0.html
  downloads/manager/5-14-1.html
  downloads/manager/5-14-2.html
  downloads/manager/5-14-3.html
  downloads/manager/5-14-4.html
  downloads/manager/5-15-0.html
  downloads/manager/5-15-1.html
  downloads/manager/5-15-2.html
  downloads/manager/5-16-1.html
  downloads/manager/5-16-2.html
  downloads/manager/5-7-0.html
  downloads/manager/5-7-1.html
  downloads/manager/5-7-2.html
  downloads/manager/5-7-4.html
  downloads/manager/5-7-5.html
  downloads/manager/5-7-6.html
  downloads/manager/5-8-0.html
  downloads/manager/5-8-1.html
  downloads/manager/5-8-2.html
  downloads/manager/5-8-3.html
  downloads/manager/5-8-4.html
  downloads/manager/5-8-5.html
  downloads/manager/5-9-0.html
  downloads/manager/5-9-1.html
  downloads/manager/5-9-2.html
  downloads/manager/5-9-3.html
  downloads/manager/6-0-0.html
  downloads/manager/6-0-1.html
  downloads/manager/6-1-0.html
  downloads/manager/6-1-1.html
  downloads/manager/6-2-0.html
  downloads/navigator/encrypt/6-2-0.html
  downloads/navigator/key-hsm/6-1-0.html
  downloads/navigator/key-trustee-kms/6-2-0.html
  downloads/navigator/key-trustee-server/5-10-0.html
  downloads/navigator/key-trustee-server/5-11-0.html
  downloads/navigator/key-trustee-server/5-12-0.html
  downloads/navigator/key-trustee-server/5-13-0.html
  downloads/navigator/key-trustee-server/5-14-0.html
  downloads/navigator/key-trustee-server/5-7-0.html
  downloads/navigator/key-trustee-server/5-8-0.html
  downloads/navigator/key-trustee-server/6-0-0.html
  downloads/navigator/key-trustee-server/6-1-0.html
  downloads/quickstart_vms.html
  downloads/quickstart_vms/5-10.html
  downloads/quickstart_vms/5-12.html
  downloads/quickstart_vms/5-13.html
  downloads/quickstart_vms/5-8.html
  legal/policies.html
  legal/terms-and-conditions.html
  partners.html
  products.html
  products/altus.html
  products/altus/access-altus-azure.html
  products/altus/altus-analytic-db.html
  products/altus/altus-data-engineering.html
  products/altus/altus-data-warehouse.html
  products/cdf.html
  products/data-science-and-engineering.html
  products/data-science-and-engineering/data-engineering.html
  products/data-science-and-engineering/data-science-workbench.html
  products/data-science-workbench.html
  products/data-warehouse.html
  products/data-warehouse/analytic-database.html
  products/data-warehouse/edw-optimization.html
  products/enterprise-data-hub.html
  products/fast-forward-labs-research.html
  products/fast-forward-labs-research/fast-forward-labs-research-reports.html
  products/fast-forward-labs-research/latest-research.html
  products/open-source/apache-hadoop/impala.html
  products/operational-db.html
  products/operational-db/operational-database.html
  products/pricing.html
  products/pricing/product-features.html
  products/product-components/cloudera-navigator.html
  products/sdx.html
  products/workload-xm.html
  resources.html
  solutions.html
  solutions/customer-insights.html
  solutions/cybersecurity.html
  solutions/gallery.html
  solutions/gallery/accenture-cyber-intelligence-platform.html
  solutions/gallery/accenture-insights-platform.html
  solutions/gallery/acxiom-marketing-analytics-environment.html
  solutions/gallery/agilelab-wide-streaming-analytics-platform.html
  solutions/gallery/amdocs-contextual-digital-engagement.html
  solutions/gallery/anomali-threatstream.html
  solutions/gallery/arcadia-data-arcadia-enterprise.html
  solutions/gallery/arcadia-data-cybersecurity-visual-analytics.html
  solutions/gallery/arcadia-visual-analytics-for-iot-data.html
  solutions/gallery/atos-codex-data-lake-engine.html
  solutions/gallery/atscale-shopper-behavior-analysis.html
  solutions/gallery/autogrid-energy-internet-platform.html
  solutions/gallery/axual-platform.html
  solutions/gallery/bardess-customer360.html
  solutions/gallery/bcs-technology-interactive-social-airline-automated-companion-isaac.html
  solutions/gallery/bluetalon.html
  solutions/gallery/booz-allen-hamilton-riskcanvas.html
  solutions/gallery/brain-management-log-intelligence-management-system-lims.html
  solutions/gallery/capgemini-leap-accelerator.html
  solutions/gallery/cask-data-application-platform.html
  solutions/gallery/cazena-big-data-as-a-service.html
  solutions/gallery/centurylink-managed-services-analytics.html
  solutions/gallery/claranet-as-a-service-on-ovh-sovereign-cloud.html
  solutions/gallery/clickfox-customer-journey-analytics-platform.html
  solutions/gallery/cognizant-bigdecisions.html
  solutions/gallery/cognizant-bigframe.html
  solutions/gallery/cognizant-customer-journey-artificial-intelligence.html
  solutions/gallery/corvil-electronic-trading-risk-and-compliance.html
  solutions/gallery/countertack-sentinel.html
  solutions/gallery/data-reply-gmbh-machine-learning-platform-for-insurance-cases.html
  solutions/gallery/datameer-network-optimization.html
  solutions/gallery/datarobot-credit-card-fraudulent-transaction.html
  solutions/gallery/datarobot-direct-marketing.html
  solutions/gallery/datavard-sap-and-hadoop-integration.html
  solutions/gallery/deloitte-converge-health-miner.html
  solutions/gallery/deloitte-customer-next-best-offer.html
  solutions/gallery/deloitte-customer360.html
  solutions/gallery/deloitte-location-based-insights-lbi.html
  solutions/gallery/denodo-data-virtualization-for-big-data.html
  solutions/gallery/digital-alchemy-udecide.html
  solutions/gallery/digital-reasoning-synthesys.html
  solutions/gallery/dxc-analytics-platform-services.html
  solutions/gallery/dxc-data-workload-optimization.html
  solutions/gallery/dxc-iot-omnilocation.html
  solutions/gallery/eVariant-Healthcare-Platform.html
  solutions/gallery/fireeye-threat-intelligence.html
  solutions/gallery/fusionex-giant.html
  solutions/gallery/informatica-customer-360-insights.html
  solutions/gallery/informatica-customer-360.html
  solutions/gallery/informatica-data-governance.html
  solutions/gallery/informatica-decision-management.html
  solutions/gallery/informatica-recommendation-engine.html
  solutions/gallery/informatica-tibco-transaction-security.html
  solutions/gallery/information-builders-dmi-accelerator-for-payments-transaction-insights.html
  solutions/gallery/information-builders-kuberre-er-360.html
  solutions/gallery/information-builders-officer-analytics-accelerator.html
  solutions/gallery/intel-apache-spot.html
  solutions/gallery/keyrus-customer-experience-excellence-c2x.html
  solutions/gallery/knime-analytics-platform.html
  solutions/gallery/kogentix-automated-machine-learning-platform-amp.html
  solutions/gallery/lockheed-leidos-caads.html
  solutions/gallery/metistream-ember.html
  solutions/gallery/metistream-Hail.html
  solutions/gallery/microstrategy-business-intelligence-platform.html
  solutions/gallery/nevis-doolytic.html
  solutions/gallery/ngdata-lily.html
  solutions/gallery/niara-security-analytics.html
  solutions/gallery/nokia-customer-experience-solutions.html
  solutions/gallery/onmarc-data-platform.html
  solutions/gallery/oracle-big-data-appliance.html
  solutions/gallery/oracle-big-data-cloud-service.html
  solutions/gallery/paxata-adaptive-information-patform.html
  solutions/gallery/pentaho-monetize-my-data.html
  solutions/gallery/pentaho-optimize-the-data-warehouse.html
  solutions/gallery/pentaho-single-view-of-patient.html
  solutions/gallery/pue-solr-datasource-for-grafana.html
  solutions/gallery/pwc-customer-insights-platform.html
  solutions/gallery/qlik-analytic-platform-for-personalized-offers.html
  solutions/gallery/qlik-customer-satisfaction-personalized-offer.html
  solutions/gallery/qlik-modernized-analytics-for-regulatory-compliance.html
  solutions/gallery/rapidminer-radoop.html
  solutions/gallery/rcg-enable-lower-business-risk.html
  solutions/gallery/rcg-enable-modernize-architecture.html
  solutions/gallery/reach-real-time-event-based-analytics-and-collaboration-hub.html
  solutions/gallery/red-hat-eurotech-end-to-end-open-source-architecture-for-iot.html
  solutions/gallery/securonix-snypr.html
  solutions/gallery/sferanet-sentiment-analysis-plus.html
  solutions/gallery/sferanet-smart-xml-platform.html
  solutions/gallery/simudyne.html
  solutions/gallery/sistematica-spa-huball.html
  solutions/gallery/streamsets-data-collector.html
  solutions/gallery/striim-real-time-data-integration-from-hpe-nonstop-to-cloudera.html
  solutions/gallery/striim-real-time-data-streaming-from-oracle-to-kafka.html
  solutions/gallery/syncsort-big-frame.html
  solutions/gallery/tableau-for-it-powered-analytics.html
  solutions/gallery/tableau-trifacta-device-analytics.html
  solutions/gallery/talend-customer-abandonment-prevention.html
  solutions/gallery/talend-fast-fraud-detection.html
  solutions/gallery/talend-game-analytics.html
  solutions/gallery/talend-transaction-analysis-optimization.html
  solutions/gallery/tcs-active-archive.html
  solutions/gallery/tcs-customer-intelligence-and-insights.html
  solutions/gallery/tcs-hobs-iras.html
  solutions/gallery/tcs-sensor-data-analytics-framework.html
  solutions/gallery/teradata-appliance-for-hadoop-with-cloudera.html
  solutions/gallery/tibco-content-spotfire-analytics.html
  solutions/gallery/tibco-spotfire-big-data-analytics.html
  solutions/gallery/trifacta-accurate-and-flexible-regulatory-reporting-on-hadoop.html
  solutions/gallery/trifacta-customer-service-analytics.html
  solutions/gallery/trifacta-wrangler-for-banking-data.html
  solutions/gallery/united-consult-real-time-location-detection-and-monitoring-system.html
  solutions/gallery/unravel-data-application-performance-management.html
  solutions/gallery/versive-security-engine.html
  solutions/gallery/zoomdata-ad-placement-optimizer.html
  solutions/gallery/zoomdata-customer-insights-solution.html
  solutions/gallery/zoomdata-real-time-network-monitor.html
  solutions/gallery/zwoox-data-ingestion-solution.html
  solutions/improve-products-and-services.html
  solutions/industry-solutions.html
  solutions/lower-business-risks.html
  solutions/lower-business-risks/general-data-protection-regulation.html
  support.html
  system/sling/logout.html
]

redirects.each do |path|
  @redirect = URI.join('https://www.cloudera.com', path)
  html = ERB.new(template, trim_mode: '%<>')
  FileUtils.mkdir_p File.dirname(path)
  File.write(path, html.result)
end
