#!/usr/env ruby -w
# frozen_string_literal: true

require 'erb'
require 'fileutils'

template = '<!DOCTYPE html>
  <html lang="en">
  <head>
  <meta charset="UTF-8">
  <title>Moved</title>
  <meta http-equiv="refresh" content="0; URL=<%= @redirect %>">
  </head>
  <body>
  <p></p>
  </body>
  </html>
'.gsub(/^  /, '')

redirects = %w[
  about.html
  about/careers.html
  about/customers.html
  about/customers/8x8.html
  about/customers/aci-worldwide.html
  about/customers/adp.html
  about/customers/allegis.html
  about/customers/atb-financial.html
  about/customers/banco-santander-spain.html
  about/customers/bank-danamon.html
  about/customers/bank-mandiri.html
  about/customers/bank-of-england.html
  about/customers/bcp.html
  about/customers/bharti-airtel.html
  about/customers/bidtellect.html
  about/customers/bt.html
  about/customers/caesarsentertainment.html
  about/customers/carlson-wagonlit-travel.html
  about/customers/cartao-elo.html
  about/customers/centrica.html
  about/customers/cerner.html
  about/customers/cisco.html
  about/customers/clearsense.html
  about/customers/cloudera-engaged.html
  about/customers/cloudera-support-interface.html
  about/customers/connexity.html
  about/customers/conversant.html
  about/customers/countertack.html
  about/customers/cox-automotive.html
  about/customers/credit-suisse.html
  about/customers/csc.html
  about/customers/cybraics.html
  about/customers/data-impact-awards.html
  about/customers/dbs-bank.html
  about/customers/dell.html
  about/customers/deutsche-telekom.html
  about/customers/dhisco.html
  about/customers/dish.html
  about/customers/docbox.html
  about/customers/docomo-digital.html
  about/customers/drawbridge.html
  about/customers/emirates-nbd.html
  about/customers/epsilon.html
  about/customers/equifax.html
  about/customers/experian.html
  about/customers/faurecia.html
  about/customers/fireeye.html
  about/customers/freddie-mac.html
  about/customers/geisinger.html
  about/customers/glaxosmithkline.html
  about/customers/globe-telecom.html
  about/customers/greentube.html
  about/customers/hellofresh.html
  about/customers/hilton.html
  about/customers/hotels-com.html
  about/customers/impact-radius.html
  about/customers/inova.html
  about/customers/iqvia.html
  about/customers/jido.html
  about/customers/jobrapido.html
  about/customers/johns-hopkins-university.html
  about/customers/kasikorn-bank.html
  about/customers/klarna.html
  about/customers/komatsu-mining.html
  about/customers/lufthansa-technik.html
  about/customers/magnify.html
  about/customers/markerstudy.html
  about/customers/mastercard.html
  about/customers/mbank.html
  about/customers/mesurio.html
  about/customers/micron.html
  about/customers/mitre.html
  about/customers/mitsubishi-fuso.html
  about/customers/national-childrens-hospital.html
  about/customers/navistar.html
  about/customers/nissan.html
  about/customers/novantas.html
  about/customers/numberly-mille-mercis-group.html
  about/customers/nyse-ice.html
  about/customers/o2.html
  about/customers/octo-telematics.html
  about/customers/odyssey.html
  about/customers/opower.html
  about/customers/orwell-group.html
  about/customers/patterns-and-predictions.html
  about/customers/persol-career.html
  about/customers/podo.html
  about/customers/prgx.html
  about/customers/pwc-cee.html
  about/customers/qsight-it.html
  about/customers/quaero.html
  about/customers/quanam.html
  about/customers/quest-diagnostics.html
  about/customers/quotient.html
  about/customers/ringcentral.html
  about/customers/rocketroi.html
  about/customers/rowan-companies.html
  about/customers/rush-university-medical-center.html
  about/customers/santander-uk.html
  about/customers/seattle-childrens.html
  about/customers/sfr.html
  about/customers/shoppermotion.html
  about/customers/sikorsky.html
  about/customers/simply-measured.html
  about/customers/sky-bet.html
  about/customers/solocal-group.html
  about/customers/symcor.html
  about/customers/t-mobile-austria.html
  about/customers/td-bank.html
  about/customers/technipfmc.html
  about/customers/telefonica.html
  about/customers/tenaris.html
  about/customers/thomson-reuters.html
  about/customers/tmw-systems.html
  about/customers/transamerica.html
  about/customers/true-corporation.html
  about/customers/unidad-editorial.html
  about/customers/united-overseas-bank.html
  about/customers/vizient.html
  about/customers/wargaming.html
  about/customers/western-union.html
  about/customers/xl-axiata.html
  about/customers/zoomlion.html
  about/customers/zoosk.html
  about/customers/zurich-insurance.html
  about/events.html
  about/events/cloudera-now.html
  about/events/cloudera-summer-school.html
  about/events/edge-to-ai-city-tour.html
  about/events/gov-forum.html
  about/events/modern-data-warehousing-fundamentals.html
  about/events/partners-summit.html
  about/events/sessions.html
  about/events/speaker-series.html
  about/events/trade-shows.html
  about/events/webinars.html
  about/investor-relations.html
  about/leadership.html
  about/locations.html
  about/news-and-blogs.html
  about/news-and-blogs/awards.html
  about/news-and-blogs/blogs.html
  about/news-and-blogs/edge-to-ai.html
  about/news-and-blogs/media-kit.html
  about/news-and-blogs/press-releases.html
  about/partners.html
  about/services-and-support.html
  about/services-and-support/fast-forward-labs.html
  about/services-and-support/professional-services.html
  about/services-and-support/support-offering.html
  about/training.html
  about/training/blended-learning.html
  about/training/certification.html
  about/training/classroom.html
  about/training/cloudera-training-administrator-technical-training-requirements.html
  about/training/cloudera-training-course-prerequisites.html
  about/training/cloudera-training-terms-and-conditions.html
  about/training/course-listing.html
  about/training/courses.html
  about/training/description-of-training-services.html
  about/training/ondemand-training.html
  about/training/private-training.html
  about/training/roles.html
  about/training/testimonials.html
  about/training/training-partner-application.html
  about/training/training-partners.html
  about/training/virtual-classroom.html
  careers.html
  contact-sales.html
  documentation.html
  downloads.html
  downloads/cdf.html
  downloads/cdf/config.html
  downloads/cdf/csp-trial.html
  downloads/cdf/csp.html
  downloads/director.html
  downloads/director/2-5-0.html
  downloads/director/2-5-1.html
  downloads/director/2-6-0.html
  downloads/director/2-6-1.html
  downloads/director/2-7-0.html
  downloads/director/2-7-1.html
  downloads/director/2-8-0.html
  downloads/director/2-8-1.html
  downloads/director/6-0-0.html
  downloads/director/6-0-1.html
  downloads/director/6-1-0.html
  downloads/director/6-2-0.html
  downloads/director/6-2-1.html
  downloads/manager.html
  downloads/manager/5-10-0.html
  downloads/manager/5-10-1.html
  downloads/manager/5-10-2.html
  downloads/manager/5-11-0.html
  downloads/manager/5-11-1.html
  downloads/manager/5-11-2.html
  downloads/manager/5-12-0.html
  downloads/manager/5-12-1.html
  downloads/manager/5-13-3.html
  downloads/manager/5-14-0.html
  downloads/manager/5-14-1.html
  downloads/manager/5-14-2.html
  downloads/manager/5-14-3.html
  downloads/manager/5-14-4.html
  downloads/manager/5-15-0.html
  downloads/manager/5-15-1.html
  downloads/manager/5-15-2.html
  downloads/manager/5-16-1.html
  downloads/manager/5-16-2.html
  downloads/manager/5-7-0.html
  downloads/manager/5-7-1.html
  downloads/manager/5-7-2.html
  downloads/manager/5-7-4.html
  downloads/manager/5-7-5.html
  downloads/manager/5-7-6.html
  downloads/manager/5-8-0.html
  downloads/manager/5-8-1.html
  downloads/manager/5-8-2.html
  downloads/manager/5-8-3.html
  downloads/manager/5-8-4.html
  downloads/manager/5-8-5.html
  downloads/manager/5-9-0.html
  downloads/manager/5-9-1.html
  downloads/manager/5-9-2.html
  downloads/manager/5-9-3.html
  downloads/manager/6-0-0.html
  downloads/manager/6-0-1.html
  downloads/manager/6-1-0.html
  downloads/manager/6-1-1.html
  downloads/manager/6-2-0.html
  downloads/quickstart_vms.html
  downloads/quickstart_vms/5-10.html
  downloads/quickstart_vms/5-12.html
  downloads/quickstart_vms/5-13.html
  downloads/quickstart_vms/5-8.html
  legal/policies.html
  legal/terms-and-conditions.html
  partners.html
  products.html
  products/altus.html
  products/altus/access-altus-azure.html
  products/altus/altus-analytic-db.html
  products/altus/altus-data-engineering.html
  products/altus/altus-data-warehouse.html
  products/cdf.html
  products/data-science-and-engineering.html
  products/data-science-and-engineering/data-engineering.html
  products/data-science-and-engineering/data-science-workbench.html
  products/data-science-workbench.html
  products/data-warehouse.html
  products/data-warehouse/analytic-database.html
  products/data-warehouse/edw-optimization.html
  products/enterprise-data-hub.html
  products/fast-forward-labs-research.html
  products/fast-forward-labs-research/fast-forward-labs-research-reports.html
  products/fast-forward-labs-research/latest-research.html
  products/operational-db.html
  products/operational-db/operational-database.html
  products/pricing.html
  products/pricing/product-features.html
  products/sdx.html
  products/workload-xm.html
  resources.html
  solutions.html
  solutions/customer-insights.html
  solutions/gallery.html
  solutions/gallery/accenture-cyber-intelligence-platform.html
  solutions/gallery/accenture-insights-platform.html
  solutions/gallery/acxiom-marketing-analytics-environment.html
  solutions/gallery/agilelab-wide-streaming-analytics-platform.html
  solutions/gallery/amdocs-contextual-digital-engagement.html
  solutions/gallery/anomali-threatstream.html
  solutions/gallery/arcadia-data-arcadia-enterprise.html
  solutions/gallery/arcadia-data-cybersecurity-visual-analytics.html
  solutions/gallery/arcadia-visual-analytics-for-iot-data.html
  solutions/gallery/atos-codex-data-lake-engine.html
  solutions/gallery/atscale-shopper-behavior-analysis.html
  solutions/gallery/autogrid-energy-internet-platform.html
  solutions/gallery/axual-platform.html
  solutions/gallery/bardess-customer360.html
  solutions/gallery/bcs-technology-interactive-social-airline-automated-companion-isaac.html
  solutions/gallery/bluetalon.html
  solutions/gallery/booz-allen-hamilton-riskcanvas.html
  solutions/gallery/brain-management-log-intelligence-management-system-lims.html
  solutions/gallery/capgemini-leap-accelerator.html
  solutions/gallery/cask-data-application-platform.html
  solutions/gallery/cazena-big-data-as-a-service.html
  solutions/gallery/centurylink-managed-services-analytics.html
  solutions/gallery/claranet-as-a-service-on-ovh-sovereign-cloud.html
  solutions/gallery/clickfox-customer-journey-analytics-platform.html
  solutions/gallery/cognizant-bigdecisions.html
  solutions/gallery/cognizant-bigframe.html
  solutions/gallery/cognizant-customer-journey-artificial-intelligence.html
  solutions/gallery/corvil-electronic-trading-risk-and-compliance.html
  solutions/gallery/countertack-sentinel.html
  solutions/gallery/data-reply-gmbh-machine-learning-platform-for-insurance-cases.html
  solutions/gallery/datameer-network-optimization.html
  solutions/gallery/datarobot-credit-card-fraudulent-transaction.html
  solutions/gallery/datarobot-direct-marketing.html
  solutions/gallery/datavard-sap-and-hadoop-integration.html
  solutions/gallery/deloitte-converge-health-miner.html
  solutions/gallery/deloitte-customer-next-best-offer.html
  solutions/gallery/deloitte-customer360.html
  solutions/gallery/deloitte-location-based-insights-lbi.html
  solutions/gallery/denodo-data-virtualization-for-big-data.html
  solutions/gallery/digital-alchemy-udecide.html
  solutions/gallery/digital-reasoning-synthesys.html
  solutions/gallery/dxc-analytics-platform-services.html
  solutions/gallery/dxc-data-workload-optimization.html
  solutions/gallery/dxc-iot-omnilocation.html
  solutions/gallery/eVariant-Healthcare-Platform.html
  solutions/gallery/fireeye-threat-intelligence.html
  solutions/gallery/fusionex-giant.html
  solutions/gallery/informatica-customer-360-insights.html
  solutions/gallery/informatica-customer-360.html
  solutions/gallery/informatica-data-governance.html
  solutions/gallery/informatica-decision-management.html
  solutions/gallery/informatica-recommendation-engine.html
  solutions/gallery/informatica-tibco-transaction-security.html
  solutions/gallery/information-builders-dmi-accelerator-for-payments-transaction-insights.html
  solutions/gallery/information-builders-kuberre-er-360.html
  solutions/gallery/information-builders-officer-analytics-accelerator.html
  solutions/gallery/intel-apache-spot.html
  solutions/gallery/keyrus-customer-experience-excellence-c2x.html
  solutions/gallery/knime-analytics-platform.html
  solutions/gallery/kogentix-automated-machine-learning-platform-amp.html
  solutions/gallery/lockheed-leidos-caads.html
  solutions/gallery/metistream-ember.html
  solutions/gallery/metistream-Hail.html
  solutions/gallery/microstrategy-business-intelligence-platform.html
  solutions/gallery/nevis-doolytic.html
  solutions/gallery/ngdata-lily.html
  solutions/gallery/niara-security-analytics.html
  solutions/gallery/nokia-customer-experience-solutions.html
  solutions/gallery/onmarc-data-platform.html
  solutions/gallery/oracle-big-data-appliance.html
  solutions/gallery/oracle-big-data-cloud-service.html
  solutions/gallery/paxata-adaptive-information-patform.html
  solutions/gallery/pentaho-monetize-my-data.html
  solutions/gallery/pentaho-optimize-the-data-warehouse.html
  solutions/gallery/pentaho-single-view-of-patient.html
  solutions/gallery/pue-solr-datasource-for-grafana.html
  solutions/gallery/pwc-customer-insights-platform.html
  solutions/gallery/qlik-analytic-platform-for-personalized-offers.html
  solutions/gallery/qlik-customer-satisfaction-personalized-offer.html
  solutions/gallery/qlik-modernized-analytics-for-regulatory-compliance.html
  solutions/gallery/rapidminer-radoop.html
  solutions/gallery/rcg-enable-lower-business-risk.html
  solutions/gallery/rcg-enable-modernize-architecture.html
  solutions/gallery/reach-real-time-event-based-analytics-and-collaboration-hub.html
  solutions/gallery/red-hat-eurotech-end-to-end-open-source-architecture-for-iot.html
  solutions/gallery/securonix-snypr.html
  solutions/gallery/sferanet-sentiment-analysis-plus.html
  solutions/gallery/sferanet-smart-xml-platform.html
  solutions/gallery/simudyne.html
  solutions/gallery/sistematica-spa-huball.html
  solutions/gallery/streamsets-data-collector.html
  solutions/gallery/striim-real-time-data-integration-from-hpe-nonstop-to-cloudera.html
  solutions/gallery/striim-real-time-data-streaming-from-oracle-to-kafka.html
  solutions/gallery/syncsort-big-frame.html
  solutions/gallery/tableau-for-it-powered-analytics.html
  solutions/gallery/tableau-trifacta-device-analytics.html
  solutions/gallery/talend-customer-abandonment-prevention.html
  solutions/gallery/talend-fast-fraud-detection.html
  solutions/gallery/talend-game-analytics.html
  solutions/gallery/talend-transaction-analysis-optimization.html
  solutions/gallery/tcs-active-archive.html
  solutions/gallery/tcs-customer-intelligence-and-insights.html
  solutions/gallery/tcs-hobs-iras.html
  solutions/gallery/tcs-sensor-data-analytics-framework.html
  solutions/gallery/teradata-appliance-for-hadoop-with-cloudera.html
  solutions/gallery/tibco-content-spotfire-analytics.html
  solutions/gallery/tibco-spotfire-big-data-analytics.html
  solutions/gallery/trifacta-accurate-and-flexible-regulatory-reporting-on-hadoop.html
  solutions/gallery/trifacta-customer-service-analytics.html
  solutions/gallery/trifacta-wrangler-for-banking-data.html
  solutions/gallery/united-consult-real-time-location-detection-and-monitoring-system.html
  solutions/gallery/unravel-data-application-performance-management.html
  solutions/gallery/versive-security-engine.html
  solutions/gallery/zoomdata-ad-placement-optimizer.html
  solutions/gallery/zoomdata-customer-insights-solution.html
  solutions/gallery/zoomdata-real-time-network-monitor.html
  solutions/gallery/zwoox-data-ingestion-solution.html
  solutions/improve-products-and-services.html
  solutions/industry-solutions.html
  solutions/lower-business-risks.html
  solutions/lower-business-risks/general-data-protection-regulation.html
  support.html
  system/sling/logout.html
]

redirects.each do |path|
  @redirect = URI.join('https://www.cloudera.com', path)
  html = ERB.new(template, trim_mode: '%<>')
  FileUtils.mkdir_p File.dirname(path)
  File.write(path, html.result)
end
