# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog,
# values which you are expected to set up once and rarely edit after
# that. If you find yourself editing this file very often, consider
# using Jekyll's data files feature for the data you need to update
# frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when
# you use 'bundle exec jekyll serve'. If you change this file, please
# restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML
# files, you will see them accessed via {{ site.title }}, {{ site.email
# }}, and so on. You can create any custom variable you would like, and
# they will be accessible in the templates via {{ site.myvariable }}.
title: Cloudera Docs
email: docs@cloudera.com
description: >- # this means to ignore newlines until "baseurl:"
  Cloudera technical documentation
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://docs-dev.cloudera.com"
twitter_username: cloudera
github_username:  cloudera

# Build settings
markdown: kramdown
#theme: minima
#plugins:
#  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - /Gemfile
  - /Gemfile.lock
  - /README.md
  - "*.bbprojectd"

  # Static content that doesn't need to be part of most builds
  - /common/fonts/
  - /common/img/
  - /common/js/libs/
  - /common/sample-data/
  - /common/themes/pre-hdp-3.1/
  - /favicon.ico
  - /sitemap.xsl

  # Static content supporting the legacy Hortonworks pages that don't
  # need to be part of most builds
  - /google313e059f6e26cb8c.html
  - /googlea675d981988e7c7a.html
  - /HDPDocuments/Cloudbreak/Cb-doc-resources/
  - /wp-content/

  # Static content supporting the legacy Cloudera pages that don't need
  # to be part of most builds
  - /apps/
  - /content/
  - /etc/
  - /etc.clientlibs/
  - /libs/

  # For development to speed up jekyll compile times, uncomment the following....
  # - /HDPDocuments/
  # - /documentation/

  # REST API Pages, generated by a third-party tool
  # - /cem/1.0.0/rest-api-reference/
  # - /cem/1.1.0/rest-api-reference/
  # - /smm/1.0.0/rest-api-reference/
  # - /smm/1.1.0/rest-api-reference/
  # - /smm/1.2.0/rest-api-reference/
  # - /smm/1.2.1/rest-api-reference/
  # - /smm/2.0.0/rest-api-reference/
  # - /srm/1.0.0/rest-api-reference/

  # Sitemap files, generated by a third-party tool
  - /best-practices/latest/sitemap.xml
  - /ccp/2.0.0/sitemap.xml
  - /ccp/2.0.1/sitemap.xml
  - /cdf-datahub/7.0.2/sitemap.xml
  - /cdp/cloud/sitemap.xml
  - /cdpdc/7.0/sitemap.xml
  - /cem/1.0.0/sitemap.xml
  - /cem/1.1.0/sitemap.xml
  - /cem/1.1.1/sitemap.xml
  - /cfm/1.0.1/sitemap.xml
  - /cloudera-manager/7.0.1/sitemap.xml
  - /cloudera-manager/7.0.3/sitemap.xml
  - /common/sitemap.xml
  - /csa/1.1.0/sitemap.xml
  - /csp/2.0.0/sitemap.xml
  - /csp/2.0.1/sitemap.xml
  - /data-catalog/cloud/sitemap.xml
  - /data-hub/cloud/sitemap.xml
  - /data-warehouse/cloud/sitemap.xml
  - /documentation/altus/sitemap.xml
  - /documentation/data-science-workbench/1-6-x/sitemap.xml
  - /documentation/data-science-workbench/1-7-x/sitemap.xml
  - /documentation/enterprise/6/6.3/sitemap.xml
  - /documentation/guru-howto/data_science/sitemap.xml
  - /documentation/guru-howto/data_warehouse/sitemap.xml
  - /documentation/kafka/4-1-x/sitemap.xml
  - /documentation/kudu/5-12-x/sitemap.xml
  - /documentation/navopt/sitemap.xml
  - /documentation/spark2/2-4-x/sitemap.xml
  - /documentation/wxm/latest/sitemap.xml
  - /HDPDocuments/Ambari/Ambari-2.5.0.3/sitemap.xml
  - /HDPDocuments/Ambari/Ambari-2.5.1.0/sitemap.xml
  - /HDPDocuments/Ambari/Ambari-2.5.2.0/sitemap.xml
  - /HDPDocuments/Ambari/Ambari-2.6.0.0/sitemap.xml
  - /HDPDocuments/Ambari/Ambari-2.6.1.0/sitemap.xml
  - /HDPDocuments/Ambari/Ambari-2.6.1.5/sitemap.xml
  - /HDPDocuments/Ambari/Ambari-2.6.2.0/sitemap.xml
  - /HDPDocuments/Ambari/Ambari-2.6.2.2/sitemap.xml
  - /HDPDocuments/Ambari/Ambari-2.7.0.0/sitemap.xml
  - /HDPDocuments/Ambari/Ambari-2.7.1.0/sitemap.xml
  - /HDPDocuments/Ambari/Ambari-2.7.3.0/sitemap.xml
  - /HDPDocuments/Ambari/Ambari-2.7.4.0/sitemap.xml
  - /HDPDocuments/Ambari/Ambari-2.7.5.0/sitemap.xml
  - /HDPDocuments/Cloudbreak/Cloudbreak-2.4.0/sitemap.xml
  - /HDPDocuments/Cloudbreak/Cloudbreak-2.4.1/sitemap.xml
  - /HDPDocuments/Cloudbreak/Cloudbreak-2.4.2/sitemap.xml
  - /HDPDocuments/Cloudbreak/Cloudbreak-2.7.1/sitemap.xml
  - /HDPDocuments/Cloudbreak/Cloudbreak-2.7.2/sitemap.xml
  - /HDPDocuments/Cloudbreak/Cloudbreak-2.9.0/sitemap.xml
  - /HDPDocuments/Cloudbreak/Cloudbreak-2.9.1/sitemap.xml
  - /HDPDocuments/DAS/DAS-1.0.0/sitemap.xml
  - /HDPDocuments/DAS/DAS-1.1.0/sitemap.xml
  - /HDPDocuments/DAS/DAS-1.2.0/sitemap.xml
  - /HDPDocuments/DAS/DAS-1.2.1/sitemap.xml
  - /HDPDocuments/DAS/DAS-1.3.0/sitemap.xml
  - /HDPDocuments/DAS/DAS-1.4.1/sitemap.xml
  - /HDPDocuments/DAS/DAS-1.4.4/sitemap.xml
  - /HDPDocuments/DLM1/DLM-1.0.0/sitemap.xml
  - /HDPDocuments/DLM1/DLM-1.1.0/sitemap.xml
  - /HDPDocuments/DLM1/DLM-1.1.2/sitemap.xml
  - /HDPDocuments/DLM1/DLM-1.2.0/sitemap.xml
  - /HDPDocuments/DLM1/DLM-1.3.0/sitemap.xml
  - /HDPDocuments/DLM1/DLM-1.4.0/sitemap.xml
  - /HDPDocuments/DLM1/DLM-1.5.0/sitemap.xml
  - /HDPDocuments/DLM1/DLM-1.5.1/sitemap.xml
  - /HDPDocuments/DP/DP-1.0.0/sitemap.xml
  - /HDPDocuments/DP/DP-1.1.0/sitemap.xml
  - /HDPDocuments/DP/DP-1.2.0/sitemap.xml
  - /HDPDocuments/DP/DP-1.2.1/sitemap.xml
  - /HDPDocuments/DP/DP-1.2.2/sitemap.xml
  - /HDPDocuments/DP/DP-1.2.3/sitemap.xml
  - /HDPDocuments/DSS1/DSS-1.0.0/sitemap.xml
  - /HDPDocuments/DSS1/DSS-1.2.1/sitemap.xml
  - /HDPDocuments/DSS1/DSS-1.2.2/sitemap.xml
  - /HDPDocuments/DSS1/DSS-1.3.0/sitemap.xml
  - /HDPDocuments/DSS1/DSS-1.3.1/sitemap.xml
  - /HDPDocuments/DSS1/DSS-1.4.0/sitemap.xml
  - /HDPDocuments/DSS1/DSS-1.5.0/sitemap.xml
  - /HDPDocuments/DSS1/DSS-1.6.0/sitemap.xml
  - /HDPDocuments/HCP1/HCP-1.1.0/sitemap.xml
  - /HDPDocuments/HCP1/HCP-1.2.0/sitemap.xml
  - /HDPDocuments/HCP1/HCP-1.2.1/sitemap.xml
  - /HDPDocuments/HCP1/HCP-1.2.2/sitemap.xml
  - /HDPDocuments/HCP1/HCP-1.3.0/sitemap.xml
  - /HDPDocuments/HCP1/HCP-1.3.1/sitemap.xml
  - /HDPDocuments/HCP1/HCP-1.4.0/sitemap.xml
  - /HDPDocuments/HCP1/HCP-1.4.1/sitemap.xml
  - /HDPDocuments/HCP1/HCP-1.4.2/sitemap.xml
  - /HDPDocuments/HCP1/HCP-1.5.0/sitemap.xml
  - /HDPDocuments/HCP1/HCP-1.5.1/sitemap.xml
  - /HDPDocuments/HCP1/HCP-1.6.0/sitemap.xml
  - /HDPDocuments/HCP1/HCP-1.6.1/sitemap.xml
  - /HDPDocuments/HCP1/HCP-1.7.0/sitemap.xml
  - /HDPDocuments/HCP1/HCP-1.7.1/sitemap.xml
  - /HDPDocuments/HCP1/HCP-1.8.0/sitemap.xml
  - /HDPDocuments/HCP1/HCP-1.9.0/sitemap.xml
  - /HDPDocuments/HCP1/HCP-1.9.1/sitemap.xml
  - /HDPDocuments/HDF2/HDF-2.1.2/sitemap.xml
  - /HDPDocuments/HDF2/HDF-2.1.4/sitemap.xml
  - /HDPDocuments/HDF3/HDF-3.0.0/sitemap.xml
  - /HDPDocuments/HDF3/HDF-3.0.1.1/sitemap.xml
  - /HDPDocuments/HDF3/HDF-3.0.1/sitemap.xml
  - /HDPDocuments/HDF3/HDF-3.0.2/sitemap.xml
  - /HDPDocuments/HDF3/HDF-3.0.3/sitemap.xml
  - /HDPDocuments/HDF3/HDF-3.1.0/sitemap.xml
  - /HDPDocuments/HDF3/HDF-3.1.1/sitemap.xml
  - /HDPDocuments/HDF3/HDF-3.1.2/sitemap.xml
  - /HDPDocuments/HDF3/HDF-3.2.0/sitemap.xml
  - /HDPDocuments/HDF3/HDF-3.3.0/sitemap.xml
  - /HDPDocuments/HDF3/HDF-3.3.1/sitemap.xml
  - /HDPDocuments/HDF3/HDF-3.4.0/sitemap.xml
  - /HDPDocuments/HDF3/HDF-3.4.1.1/sitemap.xml
  - /HDPDocuments/HDP2/HDP-2.5.6.1/sitemap.xml
  - /HDPDocuments/HDP2/HDP-2.5.6/sitemap.xml
  - /HDPDocuments/HDP2/HDP-2.6.0/sitemap.xml
  - /HDPDocuments/HDP2/HDP-2.6.1.8/sitemap.xml
  - /HDPDocuments/HDP2/HDP-2.6.1/sitemap.xml
  - /HDPDocuments/HDP2/HDP-2.6.2/sitemap.xml
  - /HDPDocuments/HDP2/HDP-2.6.3/sitemap.xml
  - /HDPDocuments/HDP2/HDP-2.6.4/sitemap.xml
  - /HDPDocuments/HDP2/HDP-2.6.5/sitemap.xml
  - /HDPDocuments/HDP3/HDP-3.0.0/sitemap.xml
  - /HDPDocuments/HDP3/HDP-3.0.1/sitemap.xml
  - /HDPDocuments/HDP3/HDP-3.1.0/sitemap.xml
  - /HDPDocuments/HDP3/HDP-3.1.4/sitemap.xml
  - /HDPDocuments/HDP3/HDP-3.1.5/sitemap.xml
  - /HDPDocuments/HDPS/HDPS-3.0.0/sitemap.xml
  - /HDPDocuments/HDPS/HDPS-4.0.0/sitemap.xml
  - /HDPDocuments/HDPS/HDPS-5.0.0/sitemap.xml
  - /HDPDocuments/SS1/SmartSense-1.4.0/sitemap.xml
  - /HDPDocuments/SS1/SmartSense-1.4.2/sitemap.xml
  - /HDPDocuments/SS1/SmartSense-1.4.3/sitemap.xml
  - /HDPDocuments/SS1/SmartSense-1.4.4/sitemap.xml
  - /HDPDocuments/SS1/SmartSense-1.4.5/sitemap.xml
  - /HDPDocuments/SS1/SmartSense-1.5.0/sitemap.xml
  - /HDPDocuments/SS1/SmartSense-1.5.1/sitemap.xml
  - /machine-learning/cloud/sitemap.xml
  - /management-console/cloud/sitemap.xml
  - /replication-manager/cloud/sitemap.xml
  - /runtime/7.0.1/sitemap.xml
  - /runtime/7.0.2/sitemap.xml
  - /runtime/7.0.3/sitemap.xml
  - /smm/2.0.0/sitemap.xml
  - /srm/1.0.0/sitemap.xml
  - /workload-manager/cloud/sitemap.xml
